# Generated by Django 3.0.3 on 2021-04-19 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigIntegerField(db_column='product_id', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
            ],
            options={
                'unique_together': {('product', 'tag')},
            },
        ),
    ]
